# Generated by Django 4.1.3 on 2022-12-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='renderedContent',
        ),
    ]
