# Generated by Django 4.1.2 on 2022-11-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tittle_tag",
            field=models.CharField(default="yoo", max_length=255),
        ),
    ]
