# Generated by Django 4.1.2 on 2022-11-15 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0002_post_tittle_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="tittle_tag",
            field=models.CharField(max_length=255),
        ),
    ]
