# Generated by Django 4.1.6 on 2023-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='kaggle_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='web_url',
            field=models.URLField(),
        ),
    ]
