# Generated by Django 4.1.6 on 2023-05-24 11:50

from django.db import migrations
import theblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_skill_work_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_history',
            name='End',
        ),
        migrations.AddField(
            model_name='work_history',
            name='end',
            field=theblog.models.PresentDateField(blank=True, null=True),
        ),
    ]
