# Generated by Django 4.1.3 on 2022-12-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tittle_tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MACHINE LEARNING', 'Ml'), ('DATA ENGINEERING', 'Data Engineering'), ('ARTIFICIAL INTELLIGENCE', 'Ai')], max_length=255),
        ),
    ]
