# Generated by Django 4.1.3 on 2022-12-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_remove_post_tittle_tag_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MACHINE LEARNING', 'Machine Learning'), ('DATA ENGINEERING', 'Data Engineering'), ('ARTIFICIAL INTELLIGENCE', 'Artificial Intelligence')], max_length=255),
        ),
    ]
